### ISSUE TITLE
Upgrade to IntelliJ IDEA 2024.1: Investigate and resolve issues with Jakarta unit test automation.

### ISSUE THREAD

**Issue by mrglavas** [OpenLiberty/liberty-tools-intellij#739]
See comments here: https://github.com/OpenLiberty/liberty-tools-intellij/issues/722#issuecomment-2093670568.

After upgrading to 2024.1, all of the Jakarta unit tests are failing with `java.lang.NoSuchMethodError: 'void org.jetbrains.idea.maven.project.MavenWorkspaceSettingsComponent.loadState(org.jetbrains.idea.maven.project.MavenWorkspaceSettings)`.
