### PR TITLE
Update lsp4mp version and cursor context handling

### PR DESCRIPTION
**Pull request by anusreelakshmi934**
Part of  #1330 

- Updated lsp4mp version to 0.17.0
- Updated referring the intellij-quarkus PR - https://github.com/redhat-developer/intellij-quarkus/pull/1517/changes#diff-84035b642c3eb4e91c1e274a1850aa32c0e06124526d183a1a57600eec027bcd

There are more compilation errors when updating to 0.17.0 which will be resolved in the upcoming PRs

### CODE REVIEW

**Review by dessina-devasia — APPROVED** [review]
Approving as all the required changes are grabbed from the intellij-quarkus PR https://github.com/redhat-developer/intellij-quarkus/pull/1517/

**Review by TrevCraw — APPROVED** [review]
